### ISSUE TITLE
Nie działa na Windows 7

### ISSUE THREAD

**Issue by KwiatekMiki** [NotroDev/SkEditorPlus#12]
Nie da się włączyć po prostu.

Informacja:
- instalowałem .net i restartowałem już ale ciagle nic, lub tak powinno być ale nwm

**Comment by NotroDev** [comment]
Aktualnie nie mam jak testować działania na Windowsie 7, więc nie mogę go wspierać. Może w przyszłości.

**Comment by KwiatekMiki** [comment]
> Aktualnie nie mam jak testować działania na Windowsie 7, więc nie mogę go wspierać. Może w przyszłości.

pisz do mnie ja mogę bez problemu

**Comment by KwiatekMiki** [comment]
a i przypominam o "Close as not planned"...
