### ISSUE TITLE
[Bug/Crash] Pasting to closed file = crash (Windows 11)

### ISSUE THREAD

**Issue by KwiatekMiki** [NotroDev/SkEditorPlus#14]
## Video
https://user-images.githubusercontent.com/79092746/205514463-62c98871-3452-4bdd-903f-f5d2f4ec8284.mp4
## System info + settings:
![image](https://user-images.githubusercontent.com/79092746/205511196-8945516c-5916-4e7b-9965-88459a415c45.png)
![image](https://user-images.githubusercontent.com/79092746/205511219-28e3b102-38ee-4439-9bc2-d71b0a40df7b.png)
![image](https://user-images.githubusercontent.com/79092746/205511226-ea8641eb-6449-4a09-ac11-c8bfc1eecb76.png)
![image](https://user-images.githubusercontent.com/79092746/205511237-dae59be4-28c3-415f-a54c-f9362dfbb9a8.png)

**Comment by KwiatekMiki** [comment]
polish???
![image](https://user-images.githubusercontent.com/79092746/205514777-c57a811e-588f-4cc8-9f4b-4f65620bd260.png)

**Comment by NotroDev** [comment]
Will be fixed in a few days
