### ISSUE TITLE
[Translation Bug] Installer (.exe) not translated

### ISSUE THREAD

**Issue by KwiatekMiki** [NotroDev/SkEditorPlus#15]
![image](https://user-images.githubusercontent.com/79092746/205516069-4b6fd97d-3b18-45cb-9cbb-8a54bc7ece09.png)
![image](https://user-images.githubusercontent.com/79092746/205516110-0065feba-a6e5-430f-872b-f0b482eaf741.png)
![image](https://user-images.githubusercontent.com/79092746/205516118-eda6f55d-115a-47df-b986-5987ed116be6.png)
etc...

**Comment by KwiatekMiki** [comment]
![image](https://user-images.githubusercontent.com/79092746/205516922-759adde7-7780-45b6-989a-f448824ae003.png)
small, SMALL??!?!?!?????

english people:
![image](https://user-images.githubusercontent.com/79092746/205516909-c7809a59-32bf-4103-a33a-932b0ca168e6.png)

**Comment by NotroDev** [comment]
Corrected (installer file was just replaced)
