### ISSUE TITLE
[Translation Bug] Polish comment in file

### ISSUE THREAD

**Issue by KwiatekMiki** [NotroDev/SkEditorPlus#16]
![image](https://user-images.githubusercontent.com/79092746/205516356-62afa16a-d212-4095-b66d-de7268d434e6.png)
### Pull request:
#17 :)

**Comment by NotroDev** [comment]
It's a file auto-generated by Visual Studio. Even if I edit it, it will be overrided after some time.
This isn't file that should be viewed by users.

**Comment by KwiatekMiki** [comment]
ok
