### ISSUE TITLE
[Translation Bug] EventGenerator.xaml not translated

### ISSUE THREAD

**Issue by KwiatekMiki** [NotroDev/SkEditorPlus#20]
![image](https://user-images.githubusercontent.com/79092746/205753233-80ca03ea-d73f-4144-8c13-66fc84028a48.png)
![image](https://user-images.githubusercontent.com/79092746/205753261-99da8e7f-5f93-4a18-b0f3-f9f82c40ae74.png)
![image](https://user-images.githubusercontent.com/79092746/205753298-fa9804c5-a32b-47d3-b3a9-957f1192fe8b.png)

**Comment by NotroDev** [comment]
This class isn't used in the app right now.
