### ISSUE TITLE
[Translation Bug] ExportOptionsWindow.xaml not translated + not existing path on my pc

### ISSUE THREAD

**Issue by KwiatekMiki** [NotroDev/SkEditorPlus#21]
![image](https://user-images.githubusercontent.com/79092746/205753561-cae4cf4d-979b-4820-b657-80cd1bed842e.png)
![image](https://user-images.githubusercontent.com/79092746/205753769-45f42437-1462-4ff9-bec1-af3819663474.png)

**Comment by NotroDev** [comment]
This class isn't used in the app right now.
