### ISSUE TITLE
Lista znalezionych błędów / nieprzyjemności  wraz z użytkowaniem

### ISSUE THREAD

**Issue by PolsatGraniePL** [NotroDev/SkEditorPlus#28]
1. Przy pierwszym włączeniu programu wyświetla: 
![image](https://user-images.githubusercontent.com/88681446/216437836-8fbcfde4-fdaf-43bc-a072-40aa11655f7d.png)

2. Podczas włączania trybu pełnoekranowego program się przycina się, jakkolwiek by to nie brzmiało (te zjawisko widać po lewym i prawym górnym rogu. Aplikacja się sama przycina się, nawet nie widać jej na drugim ekranie.)
![image](https://user-images.githubusercontent.com/88681446/216437913-b4cc36e9-bbb8-4c72-a69f-eca22546d458.png)

3. Po zamknięciu zakładek najpierw klikając prawym przyciskiem myszy, po czym zamykając ją zostaje takie coś (Trzeba wyjść i wejść do aplikacji aby usunąć ten selectbox): 
![image](https://user-images.githubusercontent.com/88681446/216438080-cdc64a55-9cc7-476b-ad03-6f8918d1582b.png)

4. Średnio edytuje się ostatnią linijkę, szczególnie kiedy zasłania ci wielki suwak (W przeciwieństwie do np. notepada++ gdzie można scrollować więcej niż do końca dokumentu):
![image](https://user-images.githubusercontent.com/88681446/216438430-3ed1f1fd-92c3-45e0-9dba-298732f33ee7.png)

5. Podczas wykonywania którejś z "szybkich akcji" wywala mi za każdym razem aplikację. 

6. Ubolewam również nad kolorowaną składnią skripta, ale to już mały drobiazg.
![image](https://user-images.githubusercontent.com/88681446/216681015-3f9f47bd-ca27-4dc8-8d53-60ed6918a3de.png)
![image](https://user-images.githubusercontent.com/88681446/216681058-9821f5f2-d747-4b51-8f4c-e13ee672c984.png)

+ brakuje mi podświetlenia takiego jak tu:
![image](https://user-images.githubusercontent.com/88681446/216681467-8b298a91-e5b5-4ca3-aafa-e0a35b1bfd34.png)
![image](https://user-images.githubusercontent.com/88681446/216681434-14b37926-364b-40a2-8eff-9f0c34a6e8d8.png)

(Błędy znalezione po pięciu minutach użytkowania, co nie zmienia faktu, że aplikacja jest bardzo dobrze wykonana.)

**Comment by NotroDev** [comment]
> Przy pierwszym włączeniu programu wyświetla:

Rzeczywiście, zrobiłem jakiś błąd, musiałem po prostu niechcący przesunąć sprawdzanie pliku podświetlania składni, przez co najpierw otwierał się plik (i wymagał tego pliku)

> Podczas włączania trybu pełnoekranowego program się przycina się, jakkolwiek by to nie brzmiało (te zjawisko widać po lewym i prawym górnym rogu. Aplikacja się sama przycina się, nawet nie widać jej na drugim ekranie.)

To jest błąd biblioteki, z której korzystam i muszę się zastanowić, co zrobić, ponieważ jest ona martwa - a cały program na niej polega.

> Po zamknięciu zakładek najpierw klikając prawym przyciskiem myszy, po czym zamykając ją zostaje takie coś (Trzeba wyjść i wejść do aplikacji aby usunąć ten selectbox):

Gdzie klikasz prawym? Klikam na kartę prawym:
![obraz](https://user-images.githubusercontent.com/77281214/216441898-a30a3c51-d1e7-4eb9-8388-60303615e33a.png)
I nic się nie dzieje.

> Średnio edytuje się ostatnią linijkę, szczególnie kiedy zasłania ci wielki suwak (W przeciwieństwie do np. notepada++ gdzie można scrollować więcej niż do końca dokumentu):

W SkEditorze+ też się da, ale nie gdy się przybliży - spróbuję to poprawić

> Podczas wykonywania którejś z "szybkich akcji" wywala mi za każdym razem aplikację.

To dziwne, pierwsze słyszę, ja również nie mam takiego problemu.
Czy mógłbyś pokazać błąd widoczny w logach windowsa? https://www.cyberlink.com/support/faq-content.do?id=10449

**Comment by PolsatGraniePL** [comment]
Crash podczas szybkiej akcji:
![image](https://user-images.githubusercontent.com/88681446/216456100-b77b1708-2dc1-4c1e-97e7-7b87b4f0eb8e.png)

**ID 1026 v1:**
> Nazwa dziennika:Application
> Źródło:        .NET Runtime
> Data:          2 lut 2023 22:40:36
> Identyfikator zdarzenia:1026
> Kategoria zadania:Brak
> Poziom:        Błędy
> Słowa kluczowe:Klasyczny
> Użytkownik:    Nie dotyczy
> Komputer:      DESKTOP-S375QOM
> Opis:
> Application: SkEditorPlus.exe
> CoreCLR Version: 6.0.1022.47605
> .NET Version: 6.0.10
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.DivideByZeroException: Attempted to divide by zero.
>    at SkEditorPlus.Windows.FormattingWindow.SpacesToTabs() in C:\Users\Notro\Desktop\Projekty\SkEditorPlus\SkEditorPlus\Windows\FormattingWindow.xaml.cs:line 117
>    at SkEditorPlus.Windows.FormattingWindow.FormatClick(Object sender, RoutedEventArgs e) in C:\Users\Notro\Desktop\Projekty\SkEditorPlus\SkEditorPlus\Windows\FormattingWindow.xaml.cs:line 40
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    at System.Windows.Controls.Primitives.ButtonBase.OnClick()
>    at System.Windows.Controls.Button.OnClick()
>    at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
>    at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
>    at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
>    at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
>    at System.Windows.Input.InputManager.ProcessStagingArea()
>    at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
>    at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
>    at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
>    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
>    at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
>    at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
>    at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
>    at System.Windows.Window.ShowHelper(Object booleanBox)
>    at System.Windows.Window.Show()
>    at System.Windows.Window.ShowDialog()
>    at SkEditorPlus.Managers.FileManager.FormatCode() in C:\Users\Notro\Desktop\Projekty\SkEditorPlus\SkEditorPlus\Managers\FileManager.cs:line 465
>    at SkEditorPlus.Functionalities.MenuBarFunc.Edit_MenuItem_Click(Object sender, RoutedEventArgs e) in C:\Users\Notro\Desktop\Projekty\SkEditorPlus\SkEditorPlus\Functionalities\MenuBarFunc.cs:line 160
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    at System.Windows.Threading.DispatcherOperation.InvokeImpl()
>    at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location ---
>    at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Windows.Threading.DispatcherOperation.Invoke()
>    at System.Windows.Threading.Dispatcher.ProcessQueue()
>    at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
>    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
>    at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
>    at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
>    at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
>    at System.Windows.Threading.Dispatcher.Run()
>    at System.Windows.Application.RunDispatcher(Object ignore)
>    at System.Windows.Application.RunInternal(Window window)
>    at System.Windows.Application.Run()
>    at SkEditorPlus.App.Main()
> 
> Kod XML zdarzenia:
> <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
>   <System>
>     <Provider Name=".NET Runtime" />
>     <EventID Qualifiers="0">1026</EventID>
>     <Version>0</Version>
>     <Level>2</Level>
>     <Task>0</Task>
>     <Opcode>0</Opcode>
>     <Keywords>0x80000000000000</Keywords>
>     <TimeCreated SystemTime="2023-02-02T21:40:36.9726569Z" />
>     <EventRecordID>55263</EventRecordID>
>     <Correlation />
>     <Execution ProcessID="0" ThreadID="0" />
>     <Channel>Application</Channel>
>     <Computer>DESKTOP-S375QOM</Computer>
>     <Security />
>   </System>
>   <EventData>
>     <Data>Application: SkEditorPlus.exe
> CoreCLR Version: 6.0.1022.47605
> .NET Version: 6.0.10
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.DivideByZeroException: Attempted to divide by zero.
>    at SkEditorPlus.Windows.FormattingWindow.SpacesToTabs() in C:\Users\Notro\Desktop\Projekty\SkEditorPlus\SkEditorPlus\Windows\FormattingWindow.xaml.cs:line 117
>    at SkEditorPlus.Windows.FormattingWindow.FormatClick(Object sender, RoutedEventArgs e) in C:\Users\Notro\Desktop\Projekty\SkEditorPlus\SkEditorPlus\Windows\FormattingWindow.xaml.cs:line 40
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    at System.Windows.Controls.Primitives.ButtonBase.OnClick()
>    at System.Windows.Controls.Button.OnClick()
>    at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
>    at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
>    at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
>    at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
>    at System.Windows.Input.InputManager.ProcessStagingArea()
>    at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
>    at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
>    at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean&amp; handled)
>    at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp; handled)
>    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp; handled)
>    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
>    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
>    at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG&amp; msg)
>    at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
>    at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
>    at System.Windows.Window.ShowHelper(Object booleanBox)
>    at System.Windows.Window.Show()
>    at System.Windows.Window.ShowDialog()
>    at SkEditorPlus.Managers.FileManager.FormatCode() in C:\Users\Notro\Desktop\Projekty\SkEditorPlus\SkEditorPlus\Managers\FileManager.cs:line 465
>    at SkEditorPlus.Functionalities.MenuBarFunc.Edit_MenuItem_Click(Object sender, RoutedEventArgs e) in C:\Users\Notro\Desktop\Projekty\SkEditorPlus\SkEditorPlus\Functionalities\MenuBarFunc.cs:line 160
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    at System.Windows.Threading.DispatcherOperation.InvokeImpl()
>    at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location ---
>    at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Windows.Threading.DispatcherOperation.Invoke()
>    at System.Windows.Threading.Dispatcher.ProcessQueue()
>    at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp; handled)
>    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp; handled)
>    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
>    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
>    at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG&amp; msg)
>    at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
>    at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
>    at System.Windows.Threading.Dispatcher.Run()
>    at System.Windows.Application.RunDispatcher(Object ignore)
>    at System.Windows.Application.RunInternal(Window window)
>    at System.Windows.Application.Run()
>    at SkEditorPlus.App.Main()
> </Data>
>   </EventData>
> </Event>

**ID 1026 v2:**
> Opis:
> Aplikacja: SkEditorPlus.exe
> Wersja architektury: v4.0.30319
> Opis: proces został przerwany z powodu nieobsłużonego wyjątku.
> Informacje o wyjątku: kod wyjątku: e0434352, adres wyjątku: 00007FFDF8F4CD29

**ID 1000:**
> Opis:
> Nazwa aplikacji powodującej błąd: SkEditorPlus.exe, wersja: 1.0.0.0, sygnatura czasowa: 0x63558578
> Nazwa modułu powodującego błąd: KERNELBASE.dll, wersja: 10.0.19041.2364, sygnatura czasowa: 0x5b7d4d22
> Kod wyjątku: 0xe0434352
> Przesunięcie błędu: 0x000000000002cd29
> Identyfikator procesu powodującego błąd: 0x2460
> Godzina uruchomienia aplikacji powodującej błąd: 0x01d9374eecee43ad
> Ścieżka aplikacji powodującej błąd: C:\Program Files (x86)\NotroDev\SkEditor+\SkEditorPlus.exe
> Ścieżka modułu powodującego błąd: C:\Windows\System32\KERNELBASE.dll
> Identyfikator raportu: f37a24a7-3f4f-45a6-a630-a1c610fc211e
> Pełna nazwa pakietu powodującego błąd: 
> Identyfikator aplikacji względem pakietu powodującego błąd:

**1001:**
> Nazwa dziennika:Application
> Źródło:        Windows Error Reporting
> Data:          2 lut 2023 22:41:02
> Identyfikator zdarzenia:1001
> Kategoria zadania:Brak
> Poziom:        Informacje
> Słowa kluczowe:Klasyczny
> Użytkownik:    Nie dotyczy
> Komputer:      DESKTOP-S375QOM
> Opis:
> Pakiet błędów 1958415628143571953, typ 4
> Nazwa zdarzenia: APPCRASH
> Odpowiedź: Niedostępny
> Identyfikator pliku CAB: 0
> 
> Podpis problemu:
> P1: SkEditorPlus.exe
> P2: 1.0.0.0
> P3: 63558578
> P4: KERNELBASE.dll
> P5: 10.0.19041.2364
> P6: 5b7d4d22
> P7: e0434352
> P8: 000000000002cd29
> P9: 
> P10: 
> 
> Dołączone pliki:
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFE28.tmp.mdmp
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1F2.tmp.WERInternalMetadata.xml
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER203.tmp.xml
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER210.tmp.csv
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER221.tmp.txt
> 
> Te pliki mogą być dostępne tutaj:
> \\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_SkEditorPlus.exe_4a6e7c3af1841daa1da127736d173623cdd3_5c88b514_f65605be-cdbc-466a-b681-c7456a33fab8
> 
> Symbol analizy: 
> Ponowne wyszukiwanie rozwiązania: 0
> Identyfikator raportu: f37a24a7-3f4f-45a6-a630-a1c610fc211e
> Stan raportu: 268435456
> Wartość skrótu pakietu: 566ad2b960bb28cc1b2db0a33e1233f1
> Identyfikator GUID pliku CAB: 0
> Kod XML zdarzenia:
> <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
>   <System>
>     <Provider Name="Windows Error Reporting" />
>     <EventID Qualifiers="0">1001</EventID>
>     <Version>0</Version>
>     <Level>4</Level>
>     <Task>0</Task>
>     <Opcode>0</Opcode>
>     <Keywords>0x80000000000000</Keywords>
>     <TimeCreated SystemTime="2023-02-02T21:41:02.1316755Z" />
>     <EventRecordID>55266</EventRecordID>
>     <Correlation />
>     <Execution ProcessID="0" ThreadID="0" />
>     <Channel>Application</Channel>
>     <Computer>DESKTOP-S375QOM</Computer>
>     <Security />
>   </System>
>   <EventData>
>     <Data>1958415628143571953</Data>
>     <Data>4</Data>
>     <Data>APPCRASH</Data>
>     <Data>Niedostępny</Data>
>     <Data>0</Data>
>     <Data>SkEditorPlus.exe</Data>
>     <Data>1.0.0.0</Data>
>     <Data>63558578</Data>
>     <Data>KERNELBASE.dll</Data>
>     <Data>10.0.19041.2364</Data>
>     <Data>5b7d4d22</Data>
>     <Data>e0434352</Data>
>     <Data>000000000002cd29</Data>
>     <Data>
>     </Data>
>     <Data>
>     </Data>
>     <Data>
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFE28.tmp.mdmp
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1F2.tmp.WERInternalMetadata.xml
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER203.tmp.xml
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER210.tmp.csv
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER221.tmp.txt</Data>
>     <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_SkEditorPlus.exe_4a6e7c3af1841daa1da127736d173623cdd3_5c88b514_f65605be-cdbc-466a-b681-c7456a33fab8</Data>
>     <Data>
>     </Data>
>     <Data>0</Data>
>     <Data>f37a24a7-3f4f-45a6-a630-a1c610fc211e</Data>
>     <Data>268435456</Data>
>     <Data>566ad2b960bb28cc1b2db0a33e1233f1</Data>
>     <Data>0</Data>
>   </EventData>
> </Event>

**Comment by NotroDev** [comment]
Ok, dzięki, na szczęście wystarczyło spojrzenie na jedną z pierwszych linijek i już wiem o co chodzi.
Jutro update z poprawkami

**Comment by PolsatGraniePL** [comment]
Attempted to divide by zero. 
![smutny_kotek](https://user-images.githubusercontent.com/88681446/216458583-813eaf06-fbe9-4cf0-bd20-700cee338a60.png)

**Comment by NotroDev** [comment]
> Attempted to divide by zero. ![smutny_kotek](https://user-images.githubusercontent.com/88681446/216458583-813eaf06-fbe9-4cf0-bd20-700cee338a60.png)

No właśnie xd
Ostatnio "ulepszylem" zamianę spacji na taby i teraz patrzy na to, ile spacji to 1 tab kodzie użytkownika (no a potem to dzieli jakoś, dlatego ten błąd), totalnie zapomniałem o sprawdzaniu, czy w ogóle jest możliwość sprawdzenia tego przez program (gdy np. kod jest pusty)

**Comment by NotroDev** [comment]
Problem 1 i 5 naprawiony.
Napisz jeszcze proszę, co z problemem 3 (moja pierwsza odpowiedź)

**Comment by PolsatGraniePL** [comment]
Kliknij PPM na ![image](https://user-images.githubusercontent.com/88681446/216680510-74592b86-b28d-4810-bb2b-bd6494984648.png) po czym kliknij LPM na ![image](https://user-images.githubusercontent.com/88681446/216680600-068c10c2-d06d-4ab3-8c8d-d70c91230b28.png), wychodzi takie coś:

![image](https://user-images.githubusercontent.com/88681446/216680186-cd87771c-a588-4868-b238-39f1b6b47718.png)

**Comment by NotroDev** [comment]
> 3. Po zamknięciu zakładek najpierw klikając prawym przyciskiem myszy, po czym zamykając ją zostaje takie coś (Trzeba wyjść i wejść do aplikacji aby usunąć ten selectbox):

Naprawione

> 6. Ubolewam również nad kolorowaną składnią skripta, ale to już mały drobiazg.

Akurat ostatnio dodawałem do podświetlenia więcej słów kluczowych (wcześniej podświetlało teraz tylko `is`, a teraz wszystkie typu `have`, `aren't`), zacząłem korzystać z regexa - no i jak widać, on zepsuł, zaraz naprawię

> 7. brakuje mi podświetlenia takiego jak tu

To przez podgląd kolorów, bez niego działa ok:
![obraz](https://user-images.githubusercontent.com/77281214/216759192-e59720dc-73a5-44be-a4b6-6deed79e795d.png)

Możliwe, że za niedługo dodam opcję wyboru, jakie podświetlanie chce użytkownik (aktualnie to jedyna opcja)

**Comment by NotroDev** [comment]
Zaktualizowałem plik składni z poprawą błędu 6, aby zaktualizować `Ustawienia` -> `Zaktualizuj plik składni`

**Comment by NotroDev** [comment]
Porozdzielałem bugi na osobne issue po angielsku.
