### ISSUE TITLE
[SUGGESTION] Custom Plugins / Auto Indentation

### ISSUE THREAD

**Issue by oShadxw** [NotroDev/SkEditorPlus#29]
I feel like these will help this grow with custom plugins adding new themes / new features.

**Comment by GliczDev** [comment]
I think SkEditor has an api (i mostly created base for it, so yeah), but as i remember, not a loader

**Comment by NotroDev** [comment]
Hey!
Thanks for suggestion.
I'll look into it soon.

**Comment by NotroDev** [comment]
Hey.
I've made a loader for plugins, and it works pretty good. I'll look if there is something to add/upgrade in this system, and later I'll make update.
