### ISSUE TITLE
[SUGGESTION] A couple suggestions

### ISSUE THREAD

**Issue by oShadxw** [NotroDev/SkEditorPlus#33]
1. Make it auto indent after a colon
2. Make the docs page go to https://skripthub.net/docs/ not SKUnity
3. Make a custom theme page so you can edit anything about the look of the editor like syntax highlighting, background, ect
4. Make an explorer so users can keep track of their files

**Comment by NotroDev** [comment]
#### Hey, thanks for your suggestions!

***

> 1. Make it auto indent after a colon

I'll see what I can do 😄 

> 2. Make the docs page go to https://skripthub.net/docs/ not SKUnity

I think it's best to add a field for entering your own link to the settings

> 3. Make a custom theme page so you can edit anything about the look of the editor like syntax highlighting, background, ect

Syntax highlighting can be edited (![tutorial](https://github.com/NotroDev/SkEditorPlus/wiki/How-to-edit-syntax-highlighting%3F)), and app's colors should be possible to edit in addons, but I'll think.

> 4. Make an explorer so users can keep track of their files

I don't know if it's what you have on your mind, but I plan to add "Projects", which are just opening folders feature (probably also in ftp).

**Comment by oShadxw** [comment]
Okay, just wanted to suggest as much as i can so you guys can get some feedback. And ima be 100% honest, right now I'm not going to use this because there's no explorer or easy way to create sk files or delete them through the editor but i do believe this has some potential. So keep up the hard work!

**Comment by NotroDev** [comment]
> Okay, just wanted to suggest as much as i can so you guys can get some feedback. And ima be 100% honest, right now I'm not going to use this because there's no explorer or easy way to create sk files or delete them through the editor but i do believe this has some potential. So keep up the hard work!

Thanks! I don't have much feedback, so I come up with what to add myself. This helps a lot :)

> **PS:** And if i can get some time i can make some contributions to hopefully help with the development 😉

Cool, thank you again ❤️

**Comment by NotroDev** [comment]
> 2. Make the docs page go to https://skripthub.net/docs/ not SKUnity
Hey, in the new update, there is a textbox in settings to enter own url (skunity is default, though).
