### ISSUE TITLE
SkEditor not opening

### ISSUE THREAD

**Issue by ItsRemix** [NotroDev/SkEditorPlus#34]
OS: Windows 11 Pro
Build: 25290.rs_prerelease.230128-1120

I tried using Installer and downloading zip and unzipping but both ways seems to not work for me. .exe dont work nor menu start application.

**Comment by NotroDev** [comment]
Hey, maybe try looking at the crash logs:
https://www.cyberlink.com/support/faq-content.do?id=10449

**Comment by NotroDev** [comment]
After talking on pv, it turned out that the culprit was an old version of .NET.
