### ISSUE TITLE
Lista Funkcji, Komend, Eventów

### ISSUE THREAD

**Issue by knugi** [NotroDev/SkEditorPlus#35]
Moja propozycja jest dodanie "outline", czyli boczny panel z listą w której linijce mamy dany Event, Komendę, Funkcję czy periodical. 
Coś w stylu co posiada Eclipse lub też inne programy do programowania.
I chyba się powtórzę, okienko projektu by się przydało, by można było wybrać plik z listy i od razu na nim operować.

Świetny program, rozwijaj dalej projekt, podoba mi się już :D 
Pozdrawiam

**Comment by NotroDev** [comment]
Hej, dzięki za propozycje :)

> Moja propozycja jest dodanie "outline", czyli boczny panel z listą w której linijce mamy dany Event, Komendę, Funkcję czy periodical.

Hmmm, jeśli dobrze rozumiem, to jest w to planach. Chodzi Ci o takie "drzewko" kodu?
To, co mam na myśli jest mniej więcej w SkIDE:
![obraz](https://user-images.githubusercontent.com/77281214/217888837-a78382b2-7912-4459-95a0-a51f030ce76c.png)
(chociaż ja i tak wolałbym to o wiele lepiej zaimplementować)

> I chyba się powtórzę, okienko projektu by się przydało, by można było wybrać plik z listy i od razu na nim operować.

Taaak, powtórzysz się :P Ten pomysł był często proponowany i tak jak wszędzie piszę mam to w planach - a nawet właśnie podczas przyjścia powiadomienia z GitHuba implementowałem to 🙂

**Comment by knugi** [comment]
`Hmmm, jeśli dobrze rozumiem, to jest w to planach. Chodzi Ci o takie "drzewko" kodu?
To, co mam na myśli jest mniej więcej w SkIDE:`
Tak właśnie o takie drzewko mi chodzi. 
Przyda się gdy mamy długi kod lub funkcje w innym pliku  i trzeba szukać eventów żeby coś zmienić.

**Comment by NotroDev** [comment]
Drzewko jest w trakcie implementacji, prawdopodobnie najcięższa część już za mną.
