### ISSUE TITLE
Niechciana automatyczna wysokość

### ISSUE THREAD

**Issue by NotroDev** [NotroDev/SkEditorPlus#4]
W generatorach pola tekstowe dopasowują swoją wysokość do długości tekstu, co powoduje nachodzenie na inne elementy:
![obraz](https://user-images.githubusercontent.com/77281214/193411306-cab7b502-777f-427f-b7f2-adeebdbb3a13.png)

**Comment by NotroDev** [comment]
Naprawione w https://github.com/NotroDev/SkEditorPlus/commit/0dd42d372a35d6bfdc7b78b7262f135e5410273f

**Comment by KwiatekMiki** [comment]
Znalazłem tego buga i zgłosiłem na skript.pl a twórca go tu skopiował :(
Link do skript.pl: https://skript.pl/temat/53624-skeditor-edytor-u%C5%82atwiaj%C4%85cy-pisanie-skrypt%C3%B3w-v2/?do=findComment&comment=326401
