### ISSUE TITLE
More Suggestions 🤙 

### ISSUE THREAD

**Issue by Outspending** [NotroDev/SkEditorPlus#43]
Hello there,

These are all my suggestions as of now. I've played with the API and the Application itself. Hopefully this will help you guys with future updates :c 

**These will include all my old suggestions that haven't been added**

- **Explorer**
  - This will help users navigate their .SK files through the explorer on the left of the text editor ( Kinda like VSC )
- **Better Indentation**
  - Right now this system isn't the best. Personally i think for you guys to improve this you need to make it auto indent 4 spaces (or 1 tab) after a : 
  - And i think you need to add indent options like 4 spaces or 1 tab
- **Addon Customization**
  - Add a way in the API to make a window to customize the addon. This will also expand the next suggestion
- **Addon Menu**
  - An addon menu will help people see information about the loaded addons and will add a way to customize the addon through the menu ( If the owner setup customization through the API )
- **Themes**
  - Add a way to make themes through the API (or the app). This can help people who don't particularly like the look of the app right now.
  - And also add a theme manager 
- **Customizable Syntax**
  - I'm aware there is already a way to customize the syntax. But i think syntax could also be edited through the API or through the panel
- **Better Tab Completion**
  - Add a way to make more tab completions through the API
  - Add more tab completion ( maybe even use the SkriptHub API )
- **Better Discord RPC**
  - Make the RPC customizable ( to some extent ) so you can add **file size, file name, opened file, line, ect**
- **Better API**
  - Add more events like (**AddonLoaded, FileOpened, AddonError, EditorError, ect**)
  - Customizable Syntax
  - Themes
  - ect

Hopefully you'll consider some of these, thanks for your time :)

**Comment by NotroDev** [comment]
Wow, thanks a lot for your feedback!

> Explorer

That's already being implemented.

> Addon Menu

I was considering that too, so it's likely going to be added.

> Themes

Technically, this can already be achieved through the built-in methods of WPF or the libraries that I'm using, but I'll try to simplify it further.

> Customizable Syntax

Same as above, it can be done, but I'll try to make it simpler.

> Better Tab Completion

Tab completion is still in testing (although it accidentally got enabled in v1.4.3), which is why it's not very helpful yet. Yes, I'm considering an API for it, but I'm currently figuring out how to implement it.

> Better Discord RPC

That's a pretty cool idea :)

>Better API
  
I haven't really focused on the API yet, which is why there are so few things available on it. Maybe I'll dedicate a whole update to it.

Thanks again!

**Comment by oShadxw** [comment]
Awesome, also i did make this in my addon. Just for some suggestions.
![image](https://user-images.githubusercontent.com/92287257/220198275-0eb77509-0c42-4e48-a6c9-638c1633c412.png)
![image](https://user-images.githubusercontent.com/92287257/220198288-909c0a2e-69db-4875-a5b1-f212cc17c486.png)

Glad to help ❤️

**Comment by NotroDev** [comment]
> Addon Menu

![obraz](https://user-images.githubusercontent.com/77281214/220429752-a55437d8-6788-43d1-8a77-296919915315.png)

In addon, it looks like this:
```cs
public class TestAddon : ISkEditorPlusAddon
{
    public SkEditorAPI skEditor;

    public string Name => "TestAddon";

    public string Author => "Notro";

    public string Description => "description";

    public string Version => "1.2.1";
}
```

It's likely that this will be included in the next update, and the addon customization will be released at a later time.

**Comment by oShadxw** [comment]
> > Addon Menu
> 
> Hey, I made it today.
> 
> ![obraz](https://user-images.githubusercontent.com/77281214/220429752-a55437d8-6788-43d1-8a77-296919915315.png)
> 
> In addon, it looks like this:
> 
> ```cs
> public class TestAddon : ISkEditorPlusAddon
> {
>     public string Name => "TestAddon";
> 
>     public string Author => "Notro";
> 
>     public string Description => "description";
> 
>     public string Version => "1.2.1";
> }
> ```
> 
> It's likely that this will be included in the next update, and the addon customization will be released at a later time.

looks great!

**Comment by oShadxw** [comment]
so uh, i made this today. Literally just the page but i can do the backend stuff later :). I'll make a Pull Request once its done.
![image](https://user-images.githubusercontent.com/92287257/220769522-67a13e73-ef72-4793-bf70-a253a20fa68d.png)

And I did add some new things to the API such as adding completions and I touched up on the completions system. I haven't implemented SkriptHub's API yet. Not sure if I will or not but :)
Hopefully this helps a bit

**Comment by NotroDev** [comment]
> so uh, i made this today. Literally just the page but i can do the backend stuff later :). I'll make a Pull Request once its done. ![image](https://user-images.githubusercontent.com/92287257/220769522-67a13e73-ef72-4793-bf70-a253a20fa68d.png) **I also edited some of the old settings pages to look more organized**
> 
> And I did add some new things to the API such as adding completions and I touched up on the completions system. I haven't implemented SkriptHub's API yet. Not sure if I will or not but :) Hopefully this helps a bit

Oh, looks cool!
Good luck!

**Comment by NotroDev** [comment]
As I said, simple addon menu was added in v1.4.4 :)

**Comment by NotroDev** [comment]
> - **Better Tab Completion**
> - Add a way to make more tab completions through the API

Hey!
I checked now and it's possible to do it already.

![obraz](https://user-images.githubusercontent.com/77281214/221549976-7a62c9ae-19dd-425d-b805-c39143d0c200.png)
![obraz](https://user-images.githubusercontent.com/77281214/221550040-867bd71f-cdc4-41f8-b87b-ccfe5430f9a8.png)

In addon, it looks like this:
```cs
public void OnLoadFinished()
{
    CompletionDataElement element = new("customAddonSnippet", "hello! you used custom addon snippet!\nhere is your caret: -> {c} <-");
    CompletionData.completionList.Add(element);
}
```

**Comment by Outspending** [comment]
> As I promised earlier, I've added a simple addon menu in version 1.4.4.
> 
> By the way, how's work going there 😉?

Hey! Sorry for the delay.
I haven't been working on it much since I'm working on my own projects and i got school.

**Comment by NotroDev** [comment]
> **Explorer**

Explorer has finally been removed from todo :)

**Comment by NotroDev** [comment]
Hello!

Many things from that list were added.
I'll close this issue now, having the rest of the suggestions in the mind.

You can create separate issues for these suggestions if you want.
