### ISSUE TITLE
The program does not start

### ISSUE THREAD

**Issue by ZConnorZ** [NotroDev/SkEditorPlus#48]
There is no understanding, but nothing happens when you open it. 
OS: Win10 Home

**Comment by NotroDev** [comment]
Hey.
I'm sorry to hear that.
Try to find some info in Event Viewer, please.
https://www.cyberlink.com/support/faq-content.do?id=10449

**Comment by ZConnorZ** [comment]
-------- Application error -----------
Name of the failed application: SkEditorPlus.exe , version: 1.5.1.0, timestamp: 0x63cf74d2
Name of the failed module: KERNELBASE.dll , version: 10.0.19041.2546, timestamp: 0xe8e9ac9b
Exception code: 0xe0434352
Error offset: 0x000000000002cd29
ID of the failed process: 0x3a28
Launch time of the failed application: 0x01d957294abbcc05
The path of the failed application: D:\MineCraft_Servers\SkEditor\SkEditorPlus.exe
The path of the failed module: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 0f9ab624-98db-4d9c-a200-1a1e936c14f3

--- other ----
https://pastebin.com/AzKbez7s

**Comment by NotroDev** [comment]
Hmm... I think that you have missing files. Try to reinstall app.

**Comment by NotroDev** [comment]
> Nothing has changed

Are you using installer or zip?

**Comment by NotroDev** [comment]
> installer

Try using zip

**Comment by ZConnorZ** [comment]
> Also, be sure that you have the latest .NET 6.0:
> https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.15-windows-x64-installer
> And that your system is 64-bit

Yes, it helped.

**Comment by NotroDev** [comment]
Great, enjoy the program :)
