### ISSUE TITLE
[Suggestion] Create a folder when it does not exist (installation path)

### ISSUE THREAD

**Issue by KwiatekMiki** [NotroDev/SkEditorPlus#49]
It would be helpful if you asked to create a folder when it doesn't exist rather than let me know about it.

### Setting unexisting path
![Setting installation path to not existing folder](https://user-images.githubusercontent.com/79092746/227606930-b2a4dd5e-cd63-409a-a182-dfc0a6053d78.png)
### Error
![Error "The specified path '/Random Software' is unavailable"](https://user-images.githubusercontent.com/79092746/227606976-4d62d352-af61-4f09-93da-5f34ae35f67e.png)

Why not do something like this:
![New error suggestion](https://user-images.githubusercontent.com/79092746/227609393-0230c9ad-da73-4557-af7d-557ad0b3deae.png)

**Comment by NotroDev** [comment]
I don't think it is possible, but I'll look into that later.

**Comment by NotroDev** [comment]
Nope. I don't think it's possible to do in [Installer Projects](https://marketplace.visualstudio.com/items?itemName=VisualStudioClient.MicrosoftVisualStudio2022InstallerProjects).
