### ISSUE TITLE
[Suggestion] Add custom Skript file icon

### ISSUE THREAD

**Issue by KwiatekMiki** [NotroDev/SkEditorPlus#51]
### My problem
For now, we don't have any custom .sk file icon
![image](https://user-images.githubusercontent.com/79092746/227610888-ca5a4b59-84f0-4ae2-82d2-34f4d756e600.png)
Why not add any?

### Examples
![image](https://user-images.githubusercontent.com/79092746/227612052-799aa545-25fc-4cce-a61f-ebea3c1c4eee.png)
![image](https://user-images.githubusercontent.com/79092746/227612210-e1f58df8-2b55-414f-b0ff-201d8f7a7848.png)

**Comment by NotroDev** [comment]
There is a icon when SkEditor+ is default editor for .sk files

**Comment by KwiatekMiki** [comment]
it wasn't showing to me.
