### ISSUE TITLE
Po otworzeniu znowu skEditora+ 2 razy, wywali.

### ISSUE THREAD

**Issue by KwiatekMiki** [NotroDev/SkEditorPlus#6]
![](https://user-images.githubusercontent.com/79092746/193911027-19f384af-fdac-4afd-ab1c-8cc4ac20fdaf.gif)

**Comment by KwiatekMiki** [comment]
Czasami może być raz, dwa lub trzy ale u mnie ciągle 2

**Comment by NotroDev** [comment]
Naprawione w https://github.com/NotroDev/SkEditorPlus/commit/579fb79c9fe0948dd55cef36ec10d31f43b0233f
