### ISSUE TITLE
Auto reload + better error reporting (Suggestions)

### ISSUE THREAD

**Issue by CroissantDuNord** [NotroDev/SkEditorPlus#62]
This will use [RCON](https://support.witherhosting.com/en/article/how-to-setup-rcon-for-your-minecraft-server-1b4jklb/), The get acces to the server console (No plugins required to use rcon), The UI, will add a reload button to send a script reload command to the server, after that, the use reload should also run when you save the file

### = if the reload is good (No error) ✅ 
The editor can display to notification to tell the user that its loaded and working

### = if the reload fail (Error) ⛔ 
Higlight the lines with error in red, show notification with the log

Concept:
![image](https://user-images.githubusercontent.com/79372025/232053321-e0643ada-ca90-46d8-a6a0-3187a03e744a.png)

**Comment by NotroDev** [comment]
It's kinda done by the Analyzer addon now (will be built-in in the future).

The skUnity Parser isn't flawless, but there's a chance I might switch to my friend's API if he makes it available (then it'll actually reload the script, similar to how Skript does it).

So, if you don't mind, I'll close this issue.
