### ISSUE TITLE
Support of the CTRL + D

### ISSUE THREAD

**Issue by skatoux** [NotroDev/SkEditorPlus#69]
Hello! I have been using skEditor for several months now and really, thank you. It answers almost perfectly to all my requests.
HOWEVER! There is one thing I find that less few code editors implement. The  "**CTRL + D**" support. When you do CTRL+D on a line, it duplicates it to the one below.

Do you think it would be possible to implement this? It's a great time saver when you want to declare several functions or parameters.
Thanks!

**Comment by skatoux** [comment]
Nice thank you! 😄

**Comment by NotroDev** [comment]
Done!
I won't release an update with just this change, thought.
But, you can have this functionality earlier! It's a pretty interesting solution, but...
Go to your SkEditor+'s installation path, remove AvalonEditB.dll file, and move here custom dll, that you can download here:
https://raw.githubusercontent.com/NotroDev/SkAvalonEdit/main/AvalonEditB.dll

**Comment by skatoux** [comment]
Huge thanks!
I just saw the answer, sorry! It works really well, it's great. I'll go much faster, thanks a lot. 😄
