### ISSUE TITLE
Możliwość zrobienia GUI " " (spacja)

### ISSUE THREAD

**Issue by KwiatekMiki** [NotroDev/SkEditorPlus#7]
![](https://user-images.githubusercontent.com/79092746/194133639-76fd439c-00a6-41b2-935e-dea3018b2ddd.gif)

**Comment by NotroDev** [comment]
Naprawione w https://github.com/NotroDev/SkEditorPlus/commit/5cf154b4f4accb2a0b281ef0c3380357b4372081
