### ISSUE TITLE
Cooldown jest wymagany w generatorze komend

### ISSUE THREAD

**Issue by KwiatekMiki** [NotroDev/SkEditorPlus#8]
![](https://user-images.githubusercontent.com/79092746/194137194-78eabc7f-9bcb-4355-87d2-3e99ab20e8f9.gif)

**Comment by NotroDev** [comment]
Naprawione w https://github.com/NotroDev/SkEditorPlus/commit/5cf154b4f4accb2a0b281ef0c3380357b4372081
