### ISSUE TITLE
SkEditor+ is sometimes on top of everything

### ISSUE THREAD

**Issue by KwiatekMiki** [NotroDev/SkEditorPlus#84]
So... I'm using this daily but it gets on top of everything and I don't know why (or anything about this). Please try to fix this.

## Video
https://github.com/NotroDev/SkEditorPlus/assets/79092746/8b9bd9c8-c855-4e0d-a069-b5d307619767

## More information
- Windows 11
- Everything else is ok
![image](https://github.com/NotroDev/SkEditorPlus/assets/79092746/612d2782-b894-436c-9d6b-b7bca706b135)
###### I have the latest version
![image](https://github.com/NotroDev/SkEditorPlus/assets/79092746/eac10f5d-9412-42d4-bba9-81f927d52b58)
###### No addons
![image](https://github.com/NotroDev/SkEditorPlus/assets/79092746/abed83b9-5a3e-4e8b-9de3-e4cf17041082)
![image](https://github.com/NotroDev/SkEditorPlus/assets/79092746/a551711c-7c9f-456b-baa5-d16ee10935e1)
###### Nothing weird to be seen here
idk what to put here more.

**Comment by KwiatekMiki** [comment]
The only thing that could have anything with it is PowerToys. I disabled "Always On Top" and it's still happening so it's not this.
(also it would have a border but it didn't have it)

![image](https://github.com/NotroDev/SkEditorPlus/assets/79092746/fac0b4c4-536f-4a6d-8bd2-e7b4a68d762c)

**Comment by NotroDev** [comment]
Hmm. So it's still a issue. I'll investigate it today.

**Comment by KwiatekMiki** [comment]
> Hmm. So it's still a issue. I'll investigate it today.

thx

**Comment by NotroDev** [comment]
Should be fixed in v1.7.8

**Comment by KwiatekMiki** [comment]
> Should be fixed in v1.7.8

thx
