### ISSUE TITLE
Indentation suggestion

### ISSUE THREAD

**Issue by ShakyTimon** [NotroDev/SkEditorPlus#87]
I would much appreciate if you could add the vscode shift + { and shift + } shortcuts, what shift + { does is indents your selected lines by one, like pressing tab on each line, but way quicker, shift + } just does the opposite and unindents your selected lines by one.

**Comment by NotroDev** [comment]
As I mentioned in the Discord server, the feature is already available, and I didn't notice it before :)
You can use the `Tab` to indent and `Shift + Tab` to unindent. These shortcuts are commonly used in most programs.
Additionally, as I mentioned earlier, it would be a great idea to include the option to customize these shortcuts in the settings.
