### ISSUE TITLE
Program wywala po otworzeniu dużego pliku (25,2 MB)

### ISSUE THREAD

**Issue by KwiatekMiki** [NotroDev/SkEditorPlus#9]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/79092746/195916100-8801ed6e-a4bc-41c1-ba81-9e03cc631a6a.gif)
(otwieranie pliku bez rozszerzenia)

**Comment by KwiatekMiki** [comment]
czemu ten gif taki mały xD

**Comment by NotroDev** [comment]
![obraz](https://user-images.githubusercontent.com/77281214/195918220-a7b3f9cf-fe4c-4422-bf1d-8e7a9964fd43.png)
Bez problemu SkEditor+ taki plik otworzył. Masz najnowszą wersję?

**Comment by KwiatekMiki** [comment]
ok mam v1.1.2 ciągle zaraz sprawdzę na v1.1.3

**Comment by KwiatekMiki** [comment]
Był ten bug TYLKO na v1.1.2-ob

**Comment by KwiatekMiki** [comment]
Dzieje się podobnie z większym plikiem

**Comment by KwiatekMiki** [comment]
closed this as "completed"
tylko że sam dodałeś label "nie zostanie naprawione"

Jak masz zamykać tak to się naucz GitHuba narpierw (albo zarządzania issue bardziej)
